"""Убрал Project_task

Revision ID: 0959c2cabfcb
Revises: 4903078811ca
Create Date: 2024-01-25 10:11:37.836951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0959c2cabfcb'
down_revision: Union[str, None] = '4903078811ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_task_id', table_name='project_task')
    op.drop_table('project_task')
    op.add_column('task', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task', 'project', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'project_id')
    op.create_table('project_task',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='project_task_project_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='project_task_task_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='project_task_pkey')
    )
    op.create_index('ix_project_task_id', 'project_task', ['id'], unique=False)
    # ### end Alembic commands ###
