"""Добавлены промежуточные таблицы к project

Revision ID: 1c0400b1dd7e
Revises: 7e3e545bca8c
Create Date: 2024-01-25 09:09:23.660236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c0400b1dd7e'
down_revision: Union[str, None] = '7e3e545bca8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_user_id'), 'project_user', ['id'], unique=False)
    op.create_table('project_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_task_id'), 'project_task', ['id'], unique=False)
    op.add_column('project', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint('project_user_id_fkey', 'project', type_='foreignkey')
    op.drop_column('project', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('project_user_id_fkey', 'project', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('project', 'name')
    op.drop_index(op.f('ix_project_task_id'), table_name='project_task')
    op.drop_table('project_task')
    op.drop_index(op.f('ix_project_user_id'), table_name='project_user')
    op.drop_table('project_user')
    # ### end Alembic commands ###
