"""Добавлена уникальность полей project_id и user_id в таблицу Projectuser

Revision ID: 2b698bc96975
Revises: c73aa14513d3
Create Date: 2024-01-28 13:44:43.729938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b698bc96975'
down_revision: Union[str, None] = 'c73aa14513d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_project_user_project_id_user_id', 'project_user', ['project_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_user_project_id_user_id', 'project_user', type_='unique')
    # ### end Alembic commands ###
