"""ghjvt;enjxyst nf,kbws bcghfdktys

Revision ID: 4903078811ca
Revises: 1c0400b1dd7e
Create Date: 2024-01-25 09:33:41.379126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4903078811ca'
down_revision: Union[str, None] = '1c0400b1dd7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_user', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('project_user_task_id_fkey', 'project_user', type_='foreignkey')
    op.create_foreign_key(None, 'project_user', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('project_user', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_user', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'project_user', type_='foreignkey')
    op.create_foreign_key('project_user_task_id_fkey', 'project_user', 'user', ['task_id'], ['id'], ondelete='SET NULL')
    op.drop_column('project_user', 'user_id')
    # ### end Alembic commands ###
