"""Убрал роль из пользователя и добавил роль в project_user

Revision ID: c12aae0cc975
Revises: 0959c2cabfcb
Create Date: 2024-01-26 09:18:12.083707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c12aae0cc975'
down_revision: Union[str, None] = '0959c2cabfcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
