"""Добавление списка  блокирующих задач которые могут быть нулями

Revision ID: c73aa14513d3
Revises: 4cc782ef3c0b
Create Date: 2024-01-28 10:52:10.446122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c73aa14513d3'
down_revision: Union[str, None] = '4cc782ef3c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('blocking_by_id', sa.Integer(), nullable=True))
    op.drop_constraint('task_blocked_by_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'task', ['blocking_by_id'], ['id'], ondelete='CASCADE')
    op.drop_column('task', 'blocked_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('blocked_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_blocked_by_id_fkey', 'task', 'task', ['blocked_by_id'], ['id'], ondelete='CASCADE')
    op.drop_column('task', 'blocking_by_id')
    # ### end Alembic commands ###
