"""Убрал роль из пользовотеля и добавил в project_user 2

Revision ID: de84493a1e63
Revises: c12aae0cc975
Create Date: 2024-01-26 09:26:56.881113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de84493a1e63'
down_revision: Union[str, None] = 'c12aae0cc975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_user', sa.Column('role', sa.Enum('meneger', 'developer', 'team_leader', 'test_engineer', name='role'), nullable=True))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', postgresql.ENUM('meneger', 'developer', 'team_leader', 'test_engineer', name='role'), autoincrement=False, nullable=True))
    op.drop_column('project_user', 'role')
    # ### end Alembic commands ###
