"""Добавление блокирующих задач

Revision ID: eaf31ed56b90
Revises: de84493a1e63
Create Date: 2024-01-28 07:05:49.104176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf31ed56b90'
down_revision: Union[str, None] = 'de84493a1e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('blocked_by_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task', 'task', ['blocked_by_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'blocked_by_id')
    # ### end Alembic commands ###
